Repository HaxeFlixel/flixel-addons, pull requests merged in 2018-06, with the labels that each got.

#320 TiledTileSet: add tile `type` and `probability` attributes
  flixel/addons/editors/tiled/TiledTileSet.hx
Labels: New Feature

#307 FlxMouseControl: distinguish mouse down from mouse drag
  flixel/addons/plugin/FlxMouseControl.hx
Labels: Bug

#305 FlxTypeText: fix applyMarkup()
  flixel/addons/text/FlxTypeText.hx
Labels: Bug

#315 TiledMap: guess rootPath based on data asset path
  flixel/addons/editors/tiled/TiledMap.hx
Labels: Improvement
